/**
 * The persisted data model -- this file is the "database schema".
 *
 * There is no server and no SQL: the whole budget is one JSON document in
 * localStorage, and the same document is what gets pushed to / pulled from the
 * shared GitHub Gist. Because that document outlives any given build, it is
 * versioned (`schemaVersion`) and upgraded by the migrations in ./migrations.ts.
 *
 * Conventions
 * -----------
 * - Money: integer minor units (see domain/money.ts). Never floats.
 * - Calendar days: 'YYYY-MM-DD' strings (see domain/date.ts). Never Date objects.
 * - Timestamps (audit/sync only, not date-scoped logic): ISO 8601 UTC strings.
 * - Ids: opaque strings, generated by newId().
 */

import type { StatusBasis } from '../domain/budget';
import type { Cents } from '../domain/money';
import type { ISODate } from '../domain/date';
import type { PeriodKey } from '../domain/period';

/** Bump this whenever the shape below changes, and add a migration. */
export const SCHEMA_VERSION = 1;

export const STORAGE_KEY = 'budgetinho.state.v1';

/** Category status colour cutoff. Spec calls this out as a tunable constant. */
export const NEAR_LIMIT_THRESHOLD = 0.8;

/**
 * How far spending may drift from elapsed time before the pace indicator stops
 * saying "on pace". 0.1 = ten percentage points either way.
 */
export const PACE_TOLERANCE = 0.1;

export interface CategoryGroup {
  id: string;
  name: string;
  sortOrder: number;
}

export type GoalType = 'target_by_date' | 'per_period';

export interface Goal {
  type: GoalType;
  /** Total to reach (target_by_date) or amount to assign each period (per_period). */
  amount: Cents;
  /** Only for target_by_date. */
  targetDate?: ISODate;
}

export interface Category {
  id: string;
  groupId: string;
  name: string;
  sortOrder: number;
  /**
   * Counts against safe-to-spend: rent, bills, anything already committed.
   * Everything else is treated as discretionary.
   */
  essential: boolean;
  goal?: Goal;
  /** Hidden from the dashboard but kept for historical reports. */
  archived?: boolean;
  notes?: string;
}

export type TransactionKind = 'expense' | 'income';

export interface Transaction {
  id: string;
  /** Calendar day; decides which period this transaction lands in. */
  date: ISODate;
  payee: string;
  /** Required for expenses, always null for income (income funds the pool). */
  categoryId: string | null;
  /** Always positive; `kind` carries the direction. */
  amount: Cents;
  kind: TransactionKind;
  memo?: string;
  createdAt: string;
  updatedAt: string;
}

/** assignments[periodKey][categoryId] = cents assigned in that period. */
export type Assignments = Record<PeriodKey, Record<string, Cents>>;

export interface GistSettings {
  /** Gist id (the hex string in the gist URL), shared by both people. */
  gistId: string;
  /** Filename inside the gist. */
  fileName: string;
  /**
   * GitHub PAT with the `gist` scope. Stored in localStorage on this device
   * only -- it is never bundled into the build and never leaves the browser
   * except as an Authorization header to api.github.com.
   */
  token: string;
  /** `updated_at` of the gist as of the last successful pull or push. */
  lastSyncedGistUpdatedAt: string | null;
  /** When this device last pulled or pushed successfully. */
  lastSyncedAt: string | null;
}

export interface Settings {
  /** 1-31. The one number the whole app pivots on. */
  periodStartDay: number;
  currency: string;
  /**
   * What the category colour cutoff is measured against.
   * 'available' = carry-over + assigned (rollover-aware, the default),
   * 'assigned'  = assigned this period only (the spec's literal wording).
   * The two agree whenever there is no carry-over.
   */
  statusBasis: StatusBasis;
  /** Overrides NEAR_LIMIT_THRESHOLD when set (Settings exposes it as a slider). */
  nearLimitThreshold: number;
  gist: GistSettings;
}

export interface BudgetState {
  schemaVersion: number;
  settings: Settings;
  groups: CategoryGroup[];
  categories: Category[];
  transactions: Transaction[];
  assignments: Assignments;
  /** Local audit stamp; also shown in Settings as "last change on this device". */
  updatedAt: string;
}

let idCounter = 0;

/** Collision-resistant enough for two humans typing on two phones. */
export function newId(prefix = 'id'): string {
  idCounter = (idCounter + 1) % 100000;
  const rand =
    typeof crypto !== 'undefined' && 'randomUUID' in crypto
      ? crypto.randomUUID().slice(0, 8)
      : Math.random().toString(36).slice(2, 10);
  return `${prefix}_${Date.now().toString(36)}${idCounter.toString(36)}${rand}`;
}

export function nowStamp(): string {
  return new Date().toISOString();
}

export function defaultGistSettings(): GistSettings {
  return {
    gistId: '',
    fileName: 'budgetinho.json',
    token: '',
    lastSyncedGistUpdatedAt: null,
    lastSyncedAt: null,
  };
}

export function defaultSettings(): Settings {
  return {
    periodStartDay: 1,
    currency: 'лв',
    statusBasis: 'available',
    nearLimitThreshold: NEAR_LIMIT_THRESHOLD,
    gist: defaultGistSettings(),
  };
}

export function emptyState(): BudgetState {
  return {
    schemaVersion: SCHEMA_VERSION,
    settings: defaultSettings(),
    groups: [],
    categories: [],
    transactions: [],
    assignments: {},
    updatedAt: nowStamp(),
  };
}
